---
name: CommandShop
author: BoxOfDevs Team
version: 1.0.0
main: BoxOfDevs\CommandShop\CommandShop
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0]
softdepend: EconomyAPI
commands: 
  cshop:
    description: ""
    usage: "/cshop <add|remove|setprice|sign|buycmd|addcmd|list|info|help> <args>"
    permission: cshop.command.manage
  buycmd:
    description: ""
    usage: "/buycmd <command>"
    permission: cshop.buy.command
permissions:
  cshop:
    default: op
    description: ""
    children:
      cshop.command.manage:
        default: op
        description: ""
      cshop.breaksign:
        default: op
        description: "
      cshop.buy:
        default: op
        description: ""
        children:
          cshop.buy.command:
            default: true
            description: ""
          cshop.buy.sign:
            default: true
            description: ""
...
