---
# Config and command/sign-database for CommandShop by BoxOfDevs:

# Messages:

buy.money.success: "Bought It Succesfully"
buy.money.miss: "Not Enough Money"

buy.item.success: ""
buy.item.miss: ""

buy.contactadmin: "ops something happend somewhere"

command.notfound: "This Command Has Been Disabled"

sign.confirm: "Tap Again To Confirm"
sign.noperm: "No Permission"
sign.nobreak: "Dont Break This Sign Or Try To"

buycmd.disabled: "This Command has Been Disabled"

# List and database of buyable commands:

commands:
  example:
    cmds: 
     - "tp {player} 123 123 123"
    buycmd: "true"
    price:
      paytype: "item"
      item: "1:0:64"

# List and database for CommandShop signs:

signs: []
...
